### ISSUE TITLE
Problems with learning RF Code

### ISSUE THREAD

**Issue by kuehfuss95** [kiwi-cam/homebridge-broadlink-rm#184]
Hi,
I've got a problem with learning RF codes. IR codes are working.
I've got a RPi 4 with Homebridge and the Broadlink RM Pro Plugin and a Broadlink RM 4 Pro.

When I'm pressing the "Scan Frequency" button in the Home-App the following log is shown on homebridge:

```
[29/12/2020, 16:37:21] [BroadlinkRM] [INFO] Scan RF (scanning)
[29/12/2020, 16:37:21] [BroadlinkRM] [ACTION] Hold down the button that sends the RF frequency.
[29/12/2020, 16:37:22] [BroadlinkRM] [INFO] Scan RF (found frequency - 1 of 2)
[29/12/2020, 16:37:22] [BroadlinkRM] [ACTION] Keep holding that button!
[29/12/2020, 16:37:23] [BroadlinkRM] [INFO] Scan RF (found frequency - 2 of 2)
[29/12/2020, 16:37:23] [BroadlinkRM] [ACTION] Press the RF button multiple times with a pause between them.
```

The problem is, that I'm not pressing any Button, but the Broadlink seems to find a frequency. If I'm pressing the button after this messages, the plugin isn't receiving anything about this...

I hope, you are able to help me!
Thanks a lot
Maik

**Comment by IgnacyWie** [comment]
I have also the same problem

**Comment by mglukhovsky** [comment]
I can confirm the same: without pressing any buttons on the remote, the plugin reports that it found both frequencies (using HOOBS and the latest version of the plugin (v4.4.0):

```
12/29/2020, 3:16:18 PM [BroadlinkRM] [INFO] Discovered Manual RM4 Pro Device (2227) at 192.168.1.178 (a4::4:1::bc::3:8::cd::c:1)
...
12/29/2020, 3:16:28 PM [BroadlinkRM] [DEBUG] ( a0:43:b0:31:ce:bf ) Packet sent: 5aa5aa555aa5aa550000000000000000000000000000000000000000000000009fcb000027226a00020000000004030001000000ccbe00009c09b238486a8adb6d5a2ab5175d23ca
12/29/2020, 3:16:28 PM [BroadlinkRM] [INFO] Scan RF (scanning)
12/29/2020, 3:16:28 PM [BroadlinkRM] [ACTION] Hold down the button that sends the RF frequency.
12/29/2020, 3:16:28 PM [BroadlinkRM] [DEBUG] ( a0:43:b0:31:ce:bf ) Packet received:  1900000000000000000000000000
[... repeats sending and receiving the same packets]
12/29/2020, 3:16:35 PM [BroadlinkRM] [INFO] Scan RF (found frequency - 1 of 2)
12/29/2020, 3:16:35 PM [BroadlinkRM] [ACTION] Keep holding that button!
12/29/2020, 3:16:36 PM [BroadlinkRM] [DEBUG] ( a0:43:b0:31:ce:bf ) Packet sent: 5aa5aa555aa5aa5500000000000000000000000000000000000000000000000022ce000027226a000a0000000004030001000000cebe000098aae71cda92de4b0bbcdb94fabb4918
12/29/2020, 3:16:36 PM [BroadlinkRM] [DEBUG] ( a0:43:b0:31:ce:bf ) Packet received:  1b00000000000000000000000000
12/29/2020, 3:16:36 PM [BroadlinkRM] [INFO] Scan RF (found frequency - 2 of 2)
12/29/2020, 3:16:36 PM [BroadlinkRM] [ACTION] Press the RF button multiple times with a pause between them.
12/29/2020, 3:16:37 PM [BroadlinkRM] [DEBUG] ( a0:43:b0:31:ce:bf ) Packet sent: 5aa5aa555aa5aa5500000000000000000000000000000000000000000000000047cc000027226a000b0000000004030001000000b7be0000e96c5a098e2e325436c4eb9ad4459b34
[... continues intermittently sending and receiving packets]
12/29/2020, 3:16:58 PM [BroadlinkRM] [DEBUG] ( a0:43:b0:31:ce:bf ) Packet received:  1e00000000000000000000000000
12/29/2020, 3:16:58 PM [BroadlinkRM] [DEBUG] ( a0:43:b0:31:ce:bf ) Packet sent: 5aa5aa555aa5aa550000000000000000000000000000000000000000000000005dcc000027226a00210000000004030001000000b7be0000e96c5a098e2e325436c4eb9ad4459b34
12/29/2020, 3:16:59 PM [BroadlinkRM] [INFO] Scan RF (stopped - 30s timeout)
12/29/2020, 3:17:00 PM [BroadlinkRM] [INFO] Scan RF (stopped)
```

**Comment by PointingP** [comment]
Also discussed in #166. Anyone tried previous versions of the plugin to see if they work? Have you updated the Broadlink FW recently also?

**Comment by kuehfuss95** [comment]
Hi, my Broadlink version is V52079. It's actual. 
I'm testing with plugin version 4.4.0. Did someone test it with a previous version?
Thanks a lot!
Maik

**Comment by adrianopery** [comment]
I tried 4.3.0, 4.3.1, 4.3.2, ....., 4.4.0 and couldn't learn the RF.
Always "Time out"

**Comment by adrianopery** [comment]
any update about it?

**Comment by masterfordev** [comment]
No. [#45](https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/45#issuecomment-741506809)

**Comment by adrianopery** [comment]
> No. [#45](https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/45#issuecomment-741506809)

My device is a RM Pro 4 and on IHC when I try to enter with the same account I already have, the message says that account is not found.

**Comment by thbenedicto** [comment]
I have also the same problem.. :(

**Comment by kiwi-cam** [comment]
@kuehfuss95 I've had some success with RF Learning recently and I've pushed some changes which work in all my testing, now I'm after BETA testers. Could you take a look at my latest comment in #45 and let me know how you get on: https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/45#issuecomment-772093495

**Comment by kiwi-cam** [comment]
Duplicate of #45

**Comment by kuehfuss95** [comment]
Hey @kiwi-cam, sorry vor being late with my answer. The RF learning is still not working yet :(
Could you please help me with this?
Trank you so much! 
my Problem is still, that I do not get any time for Scanning the RF-Frequency.

**Comment by kiwi-cam** [comment]
@kuehfuss95 what versions are you running (`npm list -g --depth=1`)? Can you enable `"debug": true`, and share your logs?

**Comment by kuehfuss95** [comment]
Hi, thanks for your answer.
Here are my answers:


![4900F699-A0DC-4CD7-97D6-D94F81FB92A8](https://user-images.githubusercontent.com/76741736/110252359-49c5a680-7f85-11eb-84b0-2f4ee2e568fb.jpeg)
![8182C736-FF2C-4B10-A099-8E794F49130B](https://user-images.githubusercontent.com/76741736/110252364-534f0e80-7f85-11eb-8471-44c6e3a8475f.jpeg)
![0F8CA385-3DF8-4DD0-A715-66CC85A35A68](https://user-images.githubusercontent.com/76741736/110252369-58ac5900-7f85-11eb-9129-13000f6703cb.jpeg)

**Comment by kiwi-cam** [comment]
@kuehfuss95 Looks like the kiwicam-broadlinkjs-rm module has an issue and is only on version 0.9.10. I'd try uninstalling this plugin and re-installing. Hopefully it'll pull the latest versions down and resolve this for you.

**Comment by kuehfuss95** [comment]
@kiwi-cam thank you! I have reinstalled the Plugin. There is just one new thing: npm ERR! invalid: kiwicam-broadlinkjs-rm@0.9.12 /usr/local/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/kiwicam-broadlinkjs-rm

**Comment by kiwi-cam** [comment]
Re-installing should've re-installed that module too. Can you uninstall, delete the folder `/usr/local/lib/node_modules/homebridge-broadlink-rm-pro`, then re-install?

**Comment by kuehfuss95** [comment]
Hi @kiwi-cam, I tested the Learning again and it worked. Thank you really much! After the new setup I will test to update the module too. Thank you!

**Comment by kuehfuss95** [comment]
Hi @kiwi-cam I tried to uninstall the plugin and delete the folder, but the folder is deleted while uninstalling. So I reinstalled the plugin and the Error "npm ERR! invalid: kiwicam-broadlinkjs-rm@0.9.12 /usr/local/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/kiwicam-broadlinkjs-rm" occures again...
Thank you very much!
