### ISSUE TITLE
Error messages with Homebridge 1.3.0

### ISSUE THREAD

**Issue by siobhanellis** [kiwi-cam/homebridge-broadlink-rm#242]
[2/20/2021, 9:18:07 AM] [Broadlink RM] Screen getCurrentPosition: 0
[2/20/2021, 9:18:07 AM] [Broadlink RM] Screen getPositionState: 2
[2/20/2021, 9:18:07 AM] [Broadlink RM] Screen getTargetPosition: 0
[2/20/2021, 9:18:07 AM] [Broadlink RM] Star Trek Tree Topper getSwitchState: undefined
[2/20/2021, 9:18:07 AM] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'On': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.
[2/20/2021, 9:18:07 AM] [Broadlink RM] Basement Door getDoorCurrentState: 1
[2/20/2021, 9:18:07 AM] [Broadlink RM] Basement Door getDoorTargetState: 1
[2/20/2021, 9:18:07 AM] [Broadlink RM] Basement Door getLockCurrentState: undefined
[2/20/2021, 9:18:07 AM] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'Lock Current State': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.

Here is my JSON

{
    "hosts": [
        {
            "mac": "34:ea:34:89:13:5a",
            "isRFSupported": true,
            "address": "192.168.1.231"
        },
        {
            "mac": "34:ea:34:8e:e1:67",
            "isRFSupported": false,
            "address": "192.168.1.208"
        }
    ],
    "accessories": [
        {
            "data": {
                "stop": "2600c6002a0f290f290f290f0e291028102710280f290f28102828100e2928100f292810281028100f290e29281028100f2a0e290e2928102810281028100e2a0e290f0003e828102810281028100e2a0e290f290e290f290f290e2928100f2928100e2928112810280f0f290f29281028100e290f290f292711280f290f28100f290f290e0003e82810290f281028100f290f280f290f290f280f290f2928100e2928100f292810281028100e290f29281028100e2a0e290f2928102810281028100e290f290f000d050000",
                "close": "2600c6002a0f2810281028100f290f290e290f290f280f2928100f290e2928100f292810281028100e292810281028100f29281028100f2928100e2928100f290e29280003cf28112711271028100f290f290e290f290f290e2928100f290e2928100f292810281028100e2a2711280f28100f29281028100f2928100e2928100f290f28280003d028102810281027110f280f290e290f290f290e2928100f290f2828100f292810281028100f292810281028100e29281028100f2928100e2928100f290f2829000d050000",
                "open": "260084002a0f290f290f290f0f291027112711271027290f102811261127290f1028290f290f2a0e290f10272a0e290f290f10282a0e290f0f281028290f10270e2a290003ce2a0e290f290f290f10281027102810281027290f102811261127290f1028290f2a0e2a0e2a0e0e29290f2a0e2a0e0f29290f2a0e0e291127290f1028102729000d0500000000"
            },
            "host": "192.168.1.208",
            "name": "Screen",
            "totalDurationClose": 16,
            "type": "window-covering",
            "totalDurationOpen": 15,
            "sendStopAt100": true
        },
        {
            "name": "Star Trek Tree Topper",
            "enableAutoOff": true,
            "data": {
                "on": "2600dc00c23111321312343111133312333214132f000238c23111321312343013133213323313133000023ec032112f1711323213123411343214113100023dc23112321311313313133312323314122f00023fc13112321212323213123312333313123200023cc13212321113313313133114333215122e00023ec13211321312313312133311343214123000023ec03311321212323312133213333314113000023ec23112311411333112143411323214133100023bc03213311311333114123313323214123100023cc132123211133230161134123035141131000d05000000000000000000000000",
                "off": "2600dc00c23111321312343111133312333214132f000238c23111321312343013133213323313133000023ec032112f1711323213123411343214113100023dc23112321311313313133312323314122f00023fc13112321212323213123312333313123200023cc13212321113313313133114333215122e00023ec13211321312313312133311343214123000023ec03311321212323312133213333314113000023ec23112311411333112143411323214133100023bc03213311311333114123313323214123100023cc132123211133230161134123035141131000d05000000000000000000000000"
            },
            "type": "switch",
            "host": "192.168.1.231",
            "onDuration": 65
        },
        {
            "autoCloseDelay": 43200,
            "debug": true,
            "data": {
                "close": "b200dc000c200c21210b210b0b210b21220b210b0b21210b0b21220a220b0b210b21220a0b220b210b21210b0b21220b0b210b210b0001560b210b21210b220b0b210b21210b210b0c20220b0b21210b220a0c200c21210b0b210b210b21220b0b21210b0b210b210b0001570b210b20220b210b0b210b21220b210b0b21210b0c20220b210b0b210b21220b0b210b210b21210b0b21220a0c210b210b0001560b210b21220b210b0b210b21210b220b0b21210b0b21210b220b0b210b21210b0b210c210b21210b0b21210b0c210b210b0001560b210b21210b220a0c0005dc000000000000000000000000",
                "open": "b200c200210b0a231f0d0a22200c200c0a220a22210c0a220a220a22200c210b0a230a220a220a0001560b210a23200c200c0a220a22200c210c0a22200c0a22200c210b0a230a22200c0a220a220a22210b210c0a220a220a220a0001570a220a22200c200d09230923200c200c0a22200c0a22200d200c0a220a231f0c0a220b220923200c200c0a220a2309220a0001570a230922200d200c0a220a22200d1f0d0a22200c0a22200c200d092309231f0d0a220a220a23200c1f0d0a220a220a220a0005dc000000000000"
            },
            "host": "192.168.1.231",
            "type": "garage-door-opener",
            "openCloseDuration": 23,
            "name": "Basement Door",
            "persistState": true
        }
    ],
    "name": "Broadlink RM",
    "platform": "BroadlinkRM",
    "hideWelcomeMessage": true
}

**Comment by Spanishu** [comment]
same here

**Comment by mitch7391** [comment]
I get this warning too.

**Comment by djchoyr** [comment]
I get the same problem. 
[homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'On': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.

the problem is recurring. jump continuously. not for pluging, but always appears in log

**Comment by obs945** [comment]
Same here and seems only rm-pro got the error messages.

**Comment by masterfordev** [comment]
> I get the same problem. 
> 
> [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'On': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.
> 
> 
> 
> the problem is recurring. jump continuously. not for pluging, but always appears in log

I dont have this issue more. Updated homebridge to 1.3.1? Many issues were fixed on that version.

**Comment by obs945** [comment]
> > I get the same problem.
> > [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'On': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.
> > the problem is recurring. jump continuously. not for pluging, but always appears in log
> 
> I dont have this issue more. Updated homebridge to 1.3.1? Many issues were fixed on that version.

Unfortunately, it still appears at version 1.3.1. 
Don't know what I can do now.

**Comment by mitch7391** [comment]
My warning for characteristic `On` is gone with Homebridge `v1.3.1`. I do however have the following warning:

```
[25/02/2021, 19:34:24] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'Outlet In Use': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
```

**Comment by Murdrock** [comment]
Same here on 1.3.1.

**Comment by masterfordev** [comment]
> Same here on 1.3.1. 

Which one?

**Comment by Murdrock** [comment]
2/28/2021, 9:01:06 AM] Error: [PARSE-ERROR] /var/lib/homebridge/plugin-persist/homebridge-broadlink-rm/4674a863ade842c441e5a79fbba962eb does not look like a valid storage file!
    at LocalStorage.parseFileSync (/usr/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/node-persist/src/local-storage.js:666:19)
    at LocalStorage.parseStorageDirSync (/usr/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/node-persist/src/local-storage.js:615:26)
    at LocalStorage.initSync (/usr/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/node-persist/src/local-storage.js:142:14)
    at Object.nodePersist.initSync (/usr/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/node-persist/src/node-persist.js:37:32)
    at Object.init (/usr/lib/node_modules/homebridge-broadlink-rm-pro/base/helpers/persistentState.js:9:15)
    at new HomebridgePlatform (/usr/lib/node_modules/homebridge-broadlink-rm-pro/base/platform.js:15:21)
    at new BroadlinkRMPlatform (/usr/lib/node_modules/homebridge-broadlink-rm-pro/platform.js:40:5)
    at /usr/lib/node_modules/homebridge/src/server.ts:377:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:312:27)
[2/28/2021, 9:01:06 AM] Got SIGTERM, shutting down Homebridge...
[2/28/2021, 9:01:11 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[2/28/2021, 9:01:16 AM] [HB Supervisor] Restarting Homebridge...
[2/28/2021, 9:01:16 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[2/28/2021, 9:01:16 AM] [HB Supervisor] Started Homebridge v1.3.1 with PID: 27173
Initializing HAP-NodeJS v0.9.2...
[2/28/2021, 9:01:17 AM] Loaded config.json with 0 accessories and 4 platforms.
[2/28/2021, 9:01:17 AM] Loaded 4 cached accessories from cachedAccessories.
[2/28/2021, 9:01:17 AM] ---
[2/28/2021, 9:01:18 AM] Loaded plugin: homebridge-broadlink-rm-pro@4.4.1
[2/28/2021, 9:01:18 AM] Registering platform 'homebridge-broadlink-rm-pro.BroadlinkRM'
[2/28/2021, 9:01:18 AM] ---
[2/28/2021, 9:01:18 AM] Loaded plugin: homebridge-camera-ffmpeg@3.1.0
[2/28/2021, 9:01:18 AM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[2/28/2021, 9:01:18 AM] ---
[2/28/2021, 9:01:18 AM] Loaded plugin: homebridge-config-ui-x@4.39.1
[2/28/2021, 9:01:18 AM] Registering platform 'homebridge-config-ui-x.config'
[2/28/2021, 9:01:18 AM] ---
[2/28/2021, 9:01:18 AM] Loaded plugin: homebridge-smtpsensor@0.1.1
[2/28/2021, 9:01:18 AM] Registering accessory 'homebridge-smtpsensor.SmtpSensor'
[2/28/2021, 9:01:18 AM] Registering platform 'homebridge-smtpsensor.SmtpSensor'
[2/28/2021, 9:01:18 AM] ---
[2/28/2021, 9:01:18 AM] Loading 4 platforms...
[2/28/2021, 9:01:18 AM] [Config] Initializing config platform...
[2/28/2021, 9:01:18 AM] [Config] Running in Service Mode
[2/28/2021, 9:01:18 AM] [Camera FFmpeg] Initializing Camera-ffmpeg platform...
[2/28/2021, 9:01:18 AM] [Camera FFmpeg] [Balcony] A videoFilter is defined, but the copy vcodec is being used. This will be ignored.
[2/28/2021, 9:01:18 AM] [Camera FFmpeg] [Stairs] A videoFilter is defined, but the copy vcodec is being used. This will be ignored.
[2/28/2021, 9:01:18 AM] [Camera FFmpeg] [Front] A videoFilter is defined, but the copy vcodec is being used. This will be ignored.
[2/28/2021, 9:01:18 AM] [Camera FFmpeg] [Back] A videoFilter is defined, but the copy vcodec is being used. This will be ignored.
[2/28/2021, 9:01:18 AM] [SmtpSensor] Initializing SmtpSensor platform...
[2/28/2021, 9:01:18 AM] Initializing platform accessory 'Stairs Sensor'...
[2/28/2021, 9:01:18 AM] Initializing platform accessory 'Front Sensor'...
[2/28/2021, 9:01:18 AM] Initializing platform accessory 'Balcony Sensor'...
[2/28/2021, 9:01:18 AM] Initializing platform accessory 'Back Sensor'...
[2/28/2021, 9:01:18 AM] [BroadlinkRM] Initializing BroadlinkRM platform...
[2/28/2021, 9:01:18 AM] Error: [PARSE-ERROR] /var/lib/homebridge/plugin-persist/homebridge-broadlink-rm/4674a863ade842c441e5a79fbba962eb does not look like a valid storage file!
    at LocalStorage.parseFileSync (/usr/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/node-persist/src/local-storage.js:666:19)
    at LocalStorage.parseStorageDirSync (/usr/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/node-persist/src/local-storage.js:615:26)

That's the log. Version 4.4.1.

**Comment by masterfordev** [comment]
Maybe you should reinstall the plugin. That isnt a normal issue 🤔

**Comment by kiwi-cam** [comment]
`/var/lib/homebridge/plugin-persist/homebridge-broadlink-rm/4674a863ade842c441e5a79fbba962eb does not look like a valid storage file!`
This comes up from time to time. Usually it's caused by an ungraceful shutdown - or something else corrupting the files.  Just delete `/var/lib/homebridge/plugin-persist/homebridge-broadlink-rm/*` and it'll start up - you'll just lose track of accessories current state.

**Comment by Spanishu** [comment]
I am getting this error message:`[08/03/2021, 09:19:21] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[08/03/2021, 09:19:21] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.`

My Json looks like this:
` {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "accessories": [
                {
                    "name": "Learn IR",
                    "host": "192.168.1.155",
                    "mac": "78:0f:77:87:f0:b8",
                    "type": "learn-code"
                },
                {
                    "name": "Aire Despacho",
                    "type": "air-conditioner",
                    "host": "192.168.1.155",
                    "mac": "78:0f:77:87:f0:b8",
                    "turnOnWhenOff": false,
                    "ignoreTemperatureWhenOff": true,
                    "temperatureFilePath": "/var/tmp/despacho.txt",
                    "autoCoolTemperature": 26,
                    "autoHeatTemperature": 23,
                    "autoSwitch": "A/C Auto Switch",
                    "temperatureUpdateFrequency": 300,
                    "minTemperature": 10,
                    "maxTemperature": 28,
                    "disableLogs": true,
                    "data": {
                        "on": "26004c0271380e290d2a0e0e0e0d0d0f0d2a0d0e0e0e0e290e290e0d0f280e0e0e0e0e290e290e0d0f280e290e0e0e0e0e290d0e0f0d0f280e0d100c0f0c0e0e0e0d0f0d0e0d0f0d0e0d0f0d0e0d0e0e0e0d0f0d0e0d0f0d0e0d0e0e0e0d0e0e0e0d0e0e0e0d0f0d0e0d0f0d0e290e290e0d0f0d0e0e0e290d0e0e290e0e0e0d0f0d0e0d0e0e0e0d0e290e290e0e0e290e290e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e290e0e0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f280d0f0e290e0e0e290e0001aa71380e290e290e0e0e0d0e0e0e290e0d0f0d0e290e290e0e0e290e0d0e0e0e290e290e0d0f280e2a0e0d0e0e0e290d0e0f0d0e290e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d100c100b100c0f0c100c0f0c0e0e0d0e0e0e0d0e0e0e0d0e0d0f0d0e0d0f0d0e0d0f0d2a0f28100c0f0c0e0e0d2a100c0c2a100c100b0d0f0d0e0d0f100c0c2b0f28100b10271027100c0f0d0f0c0f0c100c100b100c0f0d0f27100c100c0f0c0f0d0f0c100c0f0c100c0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0c100c100c0f0c100c0f0c0f0d0f0c0f0d0f0c0f0c100c0f0d0f0c0f0d0f0c0f0c100c100b100c100c0f0c100b100c0f0d0f0c0f0d0f0c0f0c100c0f0c100c100b100c0f0d0f0c100b100c0f0d0f0c0f0c10280f0c1027100c0f2810000d0500000000000000000000",
                        "off": "26004c0272360f280f290f0c0f0c100c0f280f0d0f0c0f280f28100c0f280f0c100c0f280f280f0d0f280f280f0c100c0f280f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f280f290f0c0f0c100c0f0c100c0f280f280f0d0f0c0f0d0f0c0f0d0f280f280f0c10280f280f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f280f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c100c0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f2810280f280f280f0c0f28100c0f280f0001a973360f2810280f0c0f0d0f0c0f280f0d0f0c0f280f28100c0f280f0d0f0c0f280f280f0d0f280f280f0d0f0c0f280f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f2810280f0c0f0d0f0c0f0d0f0c0f280f280f0d0f0c0f0d0f0c0f0d0f280f280f0d0f280f280f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f280f0c0f0d0f0c100c0f0c100c0f0c100c0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c100c0f0c0f0d0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c0f0d0f0c100c0f0c100c0f0c0f0d0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c10280f280f280f280f0c0f290f0c0f280f000d0500000000000000000000",
                        "cool21": {
                            "data": "2600bc0170390e2b0d0f0e0e0e0f0d2b0e0f0d0f0d0f0d0f0e2b0d0f0e2b0d2b0e0e0e2b0d2c0d2b0d2c0d2b0e0e0e0f0d2b0e0e0e0f0d0f0d0f0e0f0d0f0d2b0e2b0d2b0e2b0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d2b0e0e0e0f0d0f0d0f0e0e0e0f0d0003cc71390d2c0d0f0d0f0e0e0e2b0d0f0e0e0e0f0d0f0d2c0d0f0d2b0e2b0d0f0e2b0d2b0e2b0d2b0e2b0d0f0e0e0e2b0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d2b0e0f0d0f0d0f0d2c0d2b0e0e0e0f0d0f0d2b0e0f0d2b0e0f0d2b0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d2b0e2b0d0f0e2b0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e2b0d2b0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e2b0d0f0e2b0d2b0e2b0d0f0e2b0d2b0e000d0500000000000000000000"
                        },
                        "cool22": {
                            "data": "2600bc0170390e2b0d0f0e0e0e0f0d2b0e0f0d0f0d0f0d0f0e2b0d0f0d2c0d2b0e0e0e2b0d2c0d2b0d2c0d2b0e0e0e0f0d2b0e0e0e0f0d0f0e0e0e0e0e0f0d2b0e2b0d2b0e2b0d0f0f0d100d0f0d0d0f0f0d100d0d0f0d0f0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0d100d0f0d0d0f0f0d100d0f0d0f0d0f0e0f290f0d100d0f0d0f0d0f0d100d0f0003ca73370f2a0f0d0f0d0f0d0f2a0f0d0f0d100d0f0d0f2a0f0d0f290f2a0f0d0f2a0d2b0f2a0f290f2a0f0d0f0d0e2b0f0d0e0e0e0f0f0d0f0d0f0d100d0d0f0f0d0e0e0e0f0d0f0f0d0e0f0d0f0d0f0f0d0f0e0d2b0e0e0e0f0d0f0d2c0d2b0d0f0e0f0d0f0d0f0e2b0d2b0e0e0e2b0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d2b0e2b0d0f0d2c0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d2c0d2b0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0d0f0e2b0d2b0e2b0d2c0d2b0d0f0e2b0d2b0e000d0500000000000000000000"
                        },
                        "cool23": {
                            "data": "2600bc0170390e2b0d0f0d0f0e0f0d2b0d0f0e0f0d0f0d0f0e2b0d0f0d2b0e2b0d0f0e2b0d2b0e2b0d2b0e2b0d0f0e0e0e2b0d0f0e0e0e0f0d0f0d0f0e0f0d2b0e2b0d2b0e2b0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e2b0d0f0e0e0e0f0d0f0d0f0e0e0e0003cc71390d2b0e0f0d0f0d0f0e2b0d0f0d0f0e0e0e0f0d2b0e0f0d2b0e2b0d0f0d2c0d2b0d2c0d2b0d2c0d0f0d0f0e2b0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e2b0d0f0e0e0e0f0d2b0e2b0d0f0e0e0e0f0d2b0e2b0d2b0e0f0d2b0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d2b0e2b0d0f0e2b0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e2b0d2b0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e2b0d0f0e0e0e0f0d0f0d2c0d2b0e2b0d000d0500000000000000000000"
                        },
                        "cool24": {
                            "data": "26004c0271370f280f280f0d0e0d0e0e0e290e0e0e0d0e290e290e0e0e290e0d0e0e0e290e290e0e0e290e290e0d0e0e0e290f0d0e0d0e290e0e0e0d0e0e0f0c0e0e0e0d0f0d0f0c0e0e0e0d0f0d0e0d0f0d0e0d0e0e0f0c0f0d0f0c0f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f280f280f0d0e0d0f0d0e0d0f0d0e0d0f280f0d0f0c0f0d0f0c0f0d0f280f280f0c0f290e290f0c0f0d0f0c0f0d0f0c0f280f280f0d0f280f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0d0e0d0f0c0f0d0e0e0e0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0d0e0d0f0c0f0d0f0d0e0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0e0d0f0d0f0c0f0d0f0c0f0d0f0c0f0d0e0d0f0d0f0c0f0d0f0c0f0d0f0c0f0d0e0d0f290e290f0c0f0d0e0d0e290f280f290f0001a971380e290e290e0e0e0d0e0e0e290e0d0e0e0e290e290e0d0e2a0e0d0e0e0e290e290e0d0e2a0e290e0d0e0e0e290e0d0e0e0e290e0d0e0e0e0d0e0e0e0e0d0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e290e0d0e0e0e0e0d0e0e0d0e2a0e290e0d0e0e0e0d0e0e0e0d0e0e0e290e0d0e0e0e0d0e0e0e0d0e290e2a0e0d0e290e290e0e0e0d0e0e0e0d0e0e0e290e290e0e0e290e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0e0d0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0f0d0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0e0d0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e290e290e0e0e0d0e0e0e290e290e290e000d0500000000000000000000"
                        },
                        "cool25": {
                            "data": "26004c027236102710280f0c100b100c0f28100c0f0c10271027100c0f28100b100c0f281027100c0f281027100b100c0f28100c0f0c1027100c0f0c100c0f0d0f0c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0d0f0c0f0c1027100c0f0c100c0f0d0f0c0f281027100c0f0c100c0f0c100c0f0c1027100c0f0c100c0f0c100c0f281027100b10280f28100b100c0f0d0f0c0f0d0f271027100c0f28100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f280f28100b100c0f0d0f2710280f280f0001a973360f281027100c0f0c100c0f28100b100c0f281027100b10280f0c100c0f281027100b102710280f0c100c0f28100b100c0f28100b100c100b100c0f0c100c0f0d0f0c0f0c100c0f0d0f0c0f0c100c100b100c100b100c100b100c1027100b100c100b100c100b10280f280f0c100c0f0c100c0f0c100c0f28100b100c0f0c100c0f0c102710280f0c10271027100c0f0c100c0f0c100c0f281027100c0f280f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c10271027100c0f0c100c0f281027102710000d0500000000000000000000"
                        },
                        "cool26": {
                            "data": "26004c0271370f280f290e0d0f0c0f0d0f280f0d0f0c0f280f280f0d0f280f0c0f0d0f280f280f0d0f280f280f0c0f0d0f280f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f280f280f0d0e0d0f0d0e0d0f280f0d0f280f0c0f0d0f0c0f0d0f0c0f280f290e0d0f280f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0e290f0d0f0c0f0d0f0c0f0d0f0c0f0d0e0d0f0d0f0c0f0d0e0d0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0e0e0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0e0d0f0d0e0d0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0e0d0f0d0f0c0f0d0f0c0f0d0f0c0e0e0f280f0d0e290f280f0c0f0d0f280f280f0001a972370f280f290e0d0f0d0f0c0f280f0d0f0c0f280f280f0d0f280f0d0f0c0f280f280f0d0f280f280f0c100c0f280f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f280f280f0d0f0c0f0d0f0c0f280f0d0f280f0c0f0d0f0c0f0d0f0c0f290f280f0c0f280f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f290f0c0f0c100c0f0d0f0c0f0c100c0f0c100c0f0c100c0f0c100c0f0d0f0c0f0c100c0f0c100c0f0c100c0f0c100c0f0d0f0c0f0c100c0f0c100c0f0c100c0f0c100c0f0d0f0c0f0d0f0c0f0c100c0f0c100c0f0c100c0f0c100c0f0d0f0c0f0d0f0c0f0c100c0f0c100c0f0c100c0f0c100c0f280f0d0f280f280f0c0f0d0f280f280f000d0500000000000000000000"
                        },
                        "cool27": {
                            "data": "26004a0270390d2a0e292a0c0e0e0e2a0d0f0c0f0d2a0d2a0d0f0c2b0d0e0d100d290e290d100c2a0d2a0d0f0d0f0d290d0f0d0f0c2a0e0e0d0e0d0f0d0f0c100d0e0c0f0d0e0c100d0f0c0f0d0f0d0e0d0e0d0f0e0e0d0f0c0e0d0f0d0f0d290d0f0e0d0d0f0d0f0c100d290d2b0d0e0d0e0c100d0e0d2a0d0f0c2b0d0e0d0f0c0f0d100c0e0d2a0d2b0d0f0d290d2a0d0f0c100d0f0d0e0d0f0c0f0d0f0c0e0d2a0d100c0f0c100c0f0c100d0e0d0e0c0e0e0f0d0f0d0f0c0f0d0f0d0e0d0f0c0c100f0c0e0d0f0d0f0c0f0d0f0d0e0d0e0e0f0c0f0d0e0d0f0e0e0c0e0d100c0e0d0f0d0f0d0e0d0e0d100c0f0d0e0d0e0d0f0d0e0d0f0d0e0d100d0d0d100c0e0c100d0e0d0f0d0f0c0e0e0f0d0f0d0e0c100d290d0f0d2a0d2a0d0e0d0f0d2a0c2b0d0001ab71380d2a0d2a0d100c0f0c100b2b0d0f0e0d0d2a0e290d0e0e2a0d0e0d0f0c2b0d2a0d0f0c2b0d2a0d0e0d0f0d2a0d0f0c0f0d2a0d100c0f0c0f0d0e0d100d0d0d0f0d0f0c0f0d0e0d0f0d0e0d0f0d0e0d100c0e0d0f0d0e0c110c0e0d2a0d0f0d0e0d100d0d0c100d2a0d2a0d0f0d0e0d0e0e0e0d2a0d100d290d0e0d0f0d0e0d0f0d0f0d290d2b0d0e0d2a0d2a0d0f0d0e0d0f0d0e0c100d0e0d0f0d0e0d2a0d0f0d0e0d100c0f0c0f0d0e0d100d0d0d0f0d0e0d0f0d0f0d0e0d0e0d0f0d0e0d0f0d0f0c0f0d0e0d0f0d0e0d0f0d0f0c100c0e0d0f0d0f0c0f0d0e0d0f0d0f0c100c0f0d0e0d0e0d0f0d0f0d0e0d0f0c100d0d0d0f0d0e0d0f0d0e0e0e0d0e0d0f0d0e0d0f0e0d0d0f0d0e0e0e0d0e0d0f0d2a0e0e0c2b0d2a0d0e0d100c2a0e290d000d05000000000000000000000000"
                        },
                        "cool28": {
                            "data": "26004c0272370e290e290f0c0e0e0e0d0e290e0e0f0c0f290e290f0c0e290f0d0e0d0f280f290e0d0e290f280f0d0e0d0e290f0d0e0d0f290e0d0e0e0e0d0e0e0e0d0e0d0f0d0e0d0f0d0e0d0f0d0e0e0e0d0f0d0e0d0e0e0e0d0e0d0f0d0f0c0f290f0c0f0d0e0d0e0e0e0d0e290f280f0d0f0c0f0d0e0d0e0e0f280f280f0d0f0c0e0e0e0d0e0e0f280f280f0c0e2a0e290f0c0f0d0f0c0f0d0e0d0f0d0f0c0e0e0f280f0c0f0d0f0c0e0e0f0c0e0e0f0c0f0d0f0c0f0d0f0c0f0d0e0d0f0d0f0c0f0d0f0c0f0d0f0c0e0e0f0c0e0e0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0e0d0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f280f290e290f280f0c0f0d0f280f280f0001a972370f280f280f0d0f0c0f0d0f280f0d0f0c0f280f280f0d0f280f0c0f0d0f280f280f0d0f280f280f0c0f0d0f280f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f280f280f0d0f0c0f0d0f0c0f0d0f280f280f0c0f0d0f0c0f0d0f0c0f280f290f0c0f280f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f28100c0f0c0f0d0f0c100c0f0c100c0f0c100c0f0c0f0d0f0c0f0d0f0c100c0f0c0f0d0f0c0f0d0f0c100c0f0c0f0d0f0c0f0d0f0c100c0f0c0f0d0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0d0f0c0f0c100c0f0c100c0f0d0f0c0f0c100c0f280f280f280f28100c0f0c10280f280f000d0500000000000000000000"
                        },
                        "heat22": {
                            "data": "26004c0273360f280f28100c0f0c100c0f27100c0f0d0f2710280f0c1027100c0f0d0f271027100c10271027100c0f0d0f27100c0f0c1027100c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c100c0f0c100c0f0c0f0d0f0c100b100c100c0f0c0f0d0f280f0c100c0f0c100c0f0c1027100c0f0c100c0f0d0f0c0f281027100b100c0f0c100c100c0f0c100c0f0c100c0f280f28100b100c0f0d0f0c0f0d0f271027100c0f28100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c0f0d0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f280f28100c0f27100c0f0c10280f280f0001a9733610271027100c0f0c100c0f28100c0f0c0f281027100c0f280f0c100c0f281027100c0f2710280f0c100c0f28100b100c1027100b100c0f0c100c0f0d0f0c0f0c100c0f0c100c0f0c100c100b100c0f0c100c100c0f0c100b100c0f28100b100c0f0d0f0c0f0d0f280f0c100c0f0c100c0f0c10271027100c0f0c100c100b100c0f0d0f0c0f0d0f0c0f281027100c0f0c100c0f0d0f0c0f281027100c0f27100c0f0c100c0f0c100c100c0f0c100c0f0c0f0d0f0c0f0d0f0c0f0c100c100b100c100b100c100c0f0c100b100c100b100c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0c100c100b100c0f0c100c100b100c100b100c100b100c100b100c0f0c100c0f281027100c0f28100b100c0f28102710000d0500000000000000000000"
                        },
                        "heat23": {
                            "data": "26004c0271370e290e2a0d0e0f0d0d0e0f280d0f0d0e0d2a0e290e0e0d2a0f0d0d0e0d2a0f280e0e0d2a0d2a0d0f0d0e0d2b0c0f0d0e0d2a0e0e0d0e0e0e0d0e0d0f0d0e0e0e0d0e0d0f0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0d2a0f0d0d0e0e0e0d0e0e0e0d2a0d0f0d0e0d0f0d0e0d2a0d2b0e280e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d2a0d2a0d0f0d0e0f0d0d0e0d0f0d2a0d2a0d0e0e2a0d0e0d0f0d0e0f0d0d0e0d0f0d0e0f0d0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0e0d0d0f0d0e0d0f0d0e0d0e0f0d0d0f0d0e0d0e0e0e0d0f0e0d0d0f0d0e0d0f0e0d0d0f0d0e0d0f0d0e0d0f0d0e0f0d0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0f0d0d0e0d0f0d0e0d2a0d2a0f0d0d0e0e290e290e0001ab70390d2a0d2a0d0f0d0e0d0f0d2a0d0e0d0f0d2a0d2a0d0e0e2a0d0e0d0e0e2a0d2a0e0d0d2a0d2a0f0d0d0f0d2a0e0d0d0f0d2a0f0c0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0f0e0d0d0e0d0f0d0e0d0f0d0e0d0f0d2a100b0d0f0d0e0d0f100c0c2a100c0d0e0d0f0e0e0d2a10271027100c0f0c0d0f0f0c100c0c0f0d0f0f0c0d0f0f280f28100b100c100b100c0d0e10280f27100c0d2a100c0c0f0d0e0d0f0d0f0f0c100c0c0f0e0e0f0c0d0f0c0f0d0f0e0d0d0e0d0f100b0d0f0d0f0f0c100c0c0f100b0d0f0d0e0d0f100c0f0c0e0e0f0c0e0e0d0e0d0f0e0d100c0f0c0e0e0e0d0e0e0f0c0e0e0f0c0e0d100c100c0f0c100c0e0d0e0e0f0c100c0f0c100c0e0d100c0f0c0e0e0f0c100c0f281027100b100c1027102710000d0500000000000000000000"
                        },
                        "heat24": {
                            "data": "260010021007573b0b620a10100f0715092b0c120a100a300c2d08100a2d08130a4d0a430d2b082f0d7d0a150a2b07110b140b0d0a1509100c2b0a130a2c0b13091208130a130b460a0f0c120b120a2f07100717081408100913092d0d1108b70c2c0c0909190b100a150a0d0c2a07170b100b2c0b2b0c130b0c091709150a0d0b2c084b0b2f09130a0e0b11082e0b1009160a0c0d13091209140a0e0c1609280c0f0b110c110a100912081607120c0f071a0a120a0c0b120a1008180a2c08100b150b07124a0a0e0b0f08160b130a0e06150b110b0f0c30080f0e0e08140916090e0c2e0b110a2d0a0e09140a300b280a150912072e072f0b0001af0a075d3d0b280d2b071309140b0f0c2f091007140a2f0a2e090f0d2b0b2e09300a280c110c2a0c2c0b2c08300b2b0c2c0a0e0e120813071509110b1308140b0d0c2c0b100b110b2b08140b110b140a280c100a2e0b13090811130a120a100a2c0d0f0b110a1307130d2a0d290d2c0b110c0d0d140b0a0e0c110f0b1008150815082c0b310b0d0c100a2a051709300c280e460d100b0f09130b110b100b110b1209110b100b100c100b100b1307140a12081008150b1208120c0d0b130b120514091307140c120a120a0d0b190a0d05170d110a1004140d0e0a150b0b0e1007150c1209100a1208130a14090f0d0e0d100b110c0f09120c100c10091308130912091508110b1106160a2c092f0b100a120b2d0a2c0a000d05000000000000"
                        }
                    }
                },`
Any suggestion?

**Comment by siobhanellis** [comment]
Things have improved with 1.3.1 and 1.3.2, but still getting error messages

[3/10/2021, 10:43:06 AM] [Broadlink RM] Star Trek Tree Topper getSwitchState: undefined
[3/10/2021, 10:43:06 AM] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[3/10/2021, 10:43:06 AM] [Broadlink RM] Basement Door getDoorCurrentState: 1
[3/10/2021, 10:43:06 AM] [Broadlink RM] Basement Door getDoorTargetState: 1
[3/10/2021, 10:43:06 AM] [Broadlink RM] Basement Door getLockCurrentState: undefined
[3/10/2021, 10:43:06 AM] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'Lock Current State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[3/10/2021, 10:43:06 AM] [Broadlink RM] Basement Door getLockTargetState: undefined
[3/10/2021, 10:43:06 AM] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'Lock Target State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

Star Trek Tree Topper is a switch
Basement Door is set up as a garage door.

**Comment by masterfordev** [comment]
> Things have improved with 1.3.1 and 1.3.2, but still getting error messages
> 
> 
> 
> [3/10/2021, 10:43:06 AM] [Broadlink RM] Star Trek Tree Topper getSwitchState: undefined
> 
> [3/10/2021, 10:43:06 AM] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
> 
> [3/10/2021, 10:43:06 AM] [Broadlink RM] Basement Door getDoorCurrentState: 1
> 
> [3/10/2021, 10:43:06 AM] [Broadlink RM] Basement Door getDoorTargetState: 1
> 
> [3/10/2021, 10:43:06 AM] [Broadlink RM] Basement Door getLockCurrentState: undefined
> 
> [3/10/2021, 10:43:06 AM] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'Lock Current State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
> 
> [3/10/2021, 10:43:06 AM] [Broadlink RM] Basement Door getLockTargetState: undefined
> 
> [3/10/2021, 10:43:06 AM] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'Lock Target State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
> 
> 
> 
> Star Trek Tree Topper is a switch
> 
> Basement Door is set up as a garage door.

But the plugin works? If this works, just ignore it. @kiwi-cam will update the plugin in the next weeks. 
This is just his hobby, he work on this just in free time.

**Comment by siobhanellis** [comment]
> But the plugin works? If this works, just ignore it. @kiwi-cam will update the plugin in the next weeks.
> This is just his hobby, he work on this just in free time.

Um, I know that. I was providing extra information.

**Comment by masterfordev** [comment]
It's oks. Many accesories return an `undefined` value. I think he will fix it soon. Fortunately, the plugin still works with those errors.

**Comment by siobhanellis** [comment]
Again, I know. I was just providing extra information.

**Comment by Naqsaq** [comment]
The latest update yesterday to v4.4.2 didn't seem to solve this. I'm still getting:
`[homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.`
...every 5 minutes.

I have the temperature coming from MQTT with:
`"mqttURL": "...",
"mqttTopic": "...",
"temperatureUpdateFrequency": 300,`
...and I only publish Temperature there.

Any way to suppress these messages?

**Comment by kiwi-cam** [comment]
I'll look into it, but in the meantime you could update your config with `"noHumidity": true` so it stops querying the characteristic.

**Comment by Naqsaq** [comment]
> I'll look into it, but in the meantime you could update your config with `"noHumidity": true` so it stops querying the characteristic.

This worked - thanks!
